magassag = float(input("Kérem, adja meg a magasságát m-ben: "))
kg = float(input("Kérem, adja meg a tömegét kg-ban: "))
bmi = kg / (magassag ** 2)
bmiveg = round(bmi, 2)
alsohatar = 18.5 * (magassag ** 2)
alsoveg = round(alsohatar, 2)
felsohatar = 24.9 * (magassag ** 2)
felsoveg = round(felsohatar, 2)
print(35*"*",5*"-",35*"*",sep="")
print(f"Az ön testtömegindexe: {bmiveg} %")
print(f"Az ön magasságához az ideális testtömeg: {alsoveg} kg és {felsoveg} kg között van")